title: Lilli-Jahn-Schule Immenhausen
author: 
  name: Lilli-Jahn-Schule Immenhausen

baseURL: https://jocular-brioche-01f615.netlify.app/
languageCode: de-de
defaultContentLanguage: de
languages:
  de:
    languagedirection: rtl
    weight: 1

menu:
  footermenu:
  - Name: Intra.Net
    Weight: 100
    weight: 3
  main:
  - identifier: start
    weight: 1
    name: "Start"
    pageRef: "/_index.md"
    params:
      styleIndex: 6
  - identifier: unsere-schule
    weight: 2
    name: "Unsere Schule"
    params:
      styleIndex: 2
  - identifier: fuereltern
    weight: 3
    name: "Eltern Informationen"
    params:
      styleIndex: 3
  - identifier: foerderverein
    weight: 4
    name: "Förderverein"
    params:
      styleIndex: 4
  - identifier: kontakt
    weight: 5
    name: "Kontakt"
    pageRef: kontakt
    params:
      styleIndex: 5
markup:
  goldmark:
    renderer:
      unsafe: true
params:
  DateForm: "2.1.2006"

theme:
  - hugo-shortcode-gallery
  - schule-theme
  
galleryShowExif: false
galleryLastRow: "nojustify"
outputs:
  home:
  - "RSS"
  - "HTML"
  - "Calendar"
section: "HTML"

outputFormats:
  RSS:
    mediatype: "application/rss"
    baseName: "feed"
  Calendar:
    mediatype: "text/calendar"
    baseName: "termine-lilli-jahn-schule"

sitemap:
  changefreq: monthly
  filename: sitemap.xml

module:
  mounts:
    - source: node_modules/bootstrap/dist/js/bootstrap.bundle.min.js
      target: assets/js/bootstrap.bundle.min.js
    - source: node_modules/jquery/dist/jquery.min.js
      target: assets/js/jquery.min.js
    - source: node_modules/feather-icons/dist/feather.min.js
      target: assets/js/feather.min.js
    - source: assets
      target: assets