title: Lilli-Jahn-Schule Immenhausen
author: 
  name: Lilli-Jahn-Schule Immenhausen

baseURL: https://jocular-brioche-01f615.netlify.app/
languageCode: de-de
defaultContentLanguage: de
languages:
  de:
    languagedirection: rtl
    weight: 1

menu:
  footermenu:
  - Name: Intra.Net
    Weight: 100
    weight: 3
markup:
  goldmark:
    renderer:
      unsafe: true
params:
  DateForm: "2.1.2006"

theme: "hugo-shortcode-gallery"
galleryShowExif: false
galleryLastRow: "nojustify"
outputs:
  home:
  - "RSS"
  - "HTML"
section: "HTML"

outputFormats:
  RSS:
    mediatype: "application/rss"
    baseName: "feed"

sitemap:
  changefreq: monthly
  filename: sitemap.xml

module:
  mounts:
    - source: node_modules/bootstrap/dist/js/bootstrap.min.js
      target: assets/js/bootstrap.min.js
    - source: node_modules/jquery/dist/jquery.min.js
      target: assets/js/jquery.min.js
    - source: node_modules/popper.js/dist/popper.min.js
      target: assets/js/popper.min.js
    - source: node_modules/feather-icons/dist/feather.min.js
      target: assets/js/feather.min.js
    - source: assets
      target: assets