backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

# These lines should *not* be indented
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: post
    label: "Posts"
    folder: /content/post
    create: true
    path: "{{year}}-{{month}}-{{day}}-{{slug}}/index"
    media_folder: "images"
    public_folder: "images"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Hauptbild", name: "thumbnail", widget: "image", required: false}
      - {label: "Kategorie(n)", name: "categories", widget: "list", allow_add: true}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Fotos zum Beitrag"
        name: "images"
        widget: "image"
        required: false
        hint: "Bilder, die hier hinzugefügt werden, erscheinen automatisch unter dem Beitrag."
        media_library:
          allow_multiple: true
          config:
            multiple: true
      - label: 'Dateianhänge'
        name: 'dateianhaenge'
        widget: "file"
        required: false
        media_library:
          allow_multiple: true
          config:
            multiple: true
  - name: unsere-schule
    label: "Unsere Schule"
    folder: "content/unsere-schule"
    create: false
    media_folder: ""
    public_folder: ""
    path: '{{slug}}/index'
    nested:
      depth: 100
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: 'Cover Image', name: 'image', required: false, widget: 'image'}
      - label: "Fotos zum Beitrag"
        name: "images"
        widget: "image"
        required: false
        hint: "Bilder, die hier hinzugefügt werden, erscheinen automatisch unter dem Beitrag."
        media_library:
          allow_multiple: true
          config:
            multiple: true
      - label: 'Dateianhänge'
        name: 'dateianhaenge'
        widget: "file"
        required: false
        media_library:
          allow_multiple: true
          config:
            multiple: true
  - name: fuereltern
    label: "Für Eltern"
    folder: "content/fuereltern"
    create: false
    media_folder: ""
    public_folder: ""
    path: '{{slug}}/index'
    nested:
      depth: 100
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Fotos zum Beitrag"
        name: "images"
        widget: "image"
        required: false
        hint: "Bilder, die hier hinzugefügt werden, erscheinen automatisch unter dem Beitrag."
        media_library:
          allow_multiple: true
          config:
            multiple: true
      - label: 'Dateianhänge'
        name: 'dateianhaenge'
        widget: "file"
        required: false
        media_library:
          allow_multiple: true
          config:
            multiple: true
  - name: "pages"
    label: "Pages"
    files:
      - name: homepage
        file: "content/_index.md"
        label: "Homepage"
        fields: 
          - {label: "Body", name: "body", widget: "markdown"}
      - name: kontakt
        file: "content/kontakt.md"
        label: "Kontakt"
        fields: 
          - {label: "Body", name: "body", widget: "markdown"}
      - name: datenschutz
        file: "content/datenschutz.md"
        label: "Datenschutz"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
      - name: impressum
        file: "content/impressum.md"
        label: "Impressum"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}